#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 21 12:41:42 2019

@author: KyleRose
"""

#!/bin/bash
# Kyle A. Rose
echo "Hello, World"
echo "listing file in current directory, $PWD"
ls  # list files
$ chmod +x helloScript
